// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };


type PickContentRelationshipFieldData<
	TRelationship extends prismic.CustomTypeModelFetchCustomTypeLevel1 | prismic.CustomTypeModelFetchCustomTypeLevel2 | prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<string, prismic.AnyRegularField | prismic.GroupField | prismic.NestedGroupField | prismic.SliceZone>,
	TLang extends string
> = |
	// Content relationship fields
	{
		[TSubRelationship in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchContentRelationshipLevel1
		> as TSubRelationship["id"]]:
			ContentRelationshipFieldWithData<TSubRelationship["customtypes"], TLang>;
	} &
	// Group
	{
		[TGroup in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2
		> as TGroup["id"]]:
			TData[TGroup["id"]] extends prismic.GroupField<infer TGroupData>
				? prismic.GroupField<PickContentRelationshipFieldData<TGroup, TGroupData, TLang>>
				: never
	} &
	// Other fields
	{
		[TFieldKey in Extract<TRelationship["fields"][number], string>]:
			TFieldKey extends keyof TData ? TData[TFieldKey] : never;
	};

type ContentRelationshipFieldWithData<
	TCustomType extends readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[] | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string
> = {
	[ID in Exclude<TCustomType[number], string>["id"]]:
		prismic.ContentRelationshipField<
			ID,
			TLang,
			PickContentRelationshipFieldData<
				Extract<TCustomType[number], { id: ID }>,
				Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
				TLang
			>
		>
}[Exclude<TCustomType[number], string>["id"]];

type EnterPageDocumentDataSlicesSlice = HeroSlice | RichTextSlice

/**
 * Content for Enter Page documents
 */
interface EnterPageDocumentData {
	/**
	 * Slice Zone field in *Enter Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: enter_page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<EnterPageDocumentDataSlicesSlice>;/**
	 * Price per book (single entry) field in *Enter Page*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: 40
	 * - **API ID Path**: enter_page.price_single_book
	 * - **Tab**: Entry Settings
	 * - **Documentation**: https://prismic.io/docs/fields/number
	 */
	price_single_book: prismic.NumberField;
	
	/**
	 * Price per book (2+ entries) field in *Enter Page*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: 35
	 * - **API ID Path**: enter_page.price_multiple_books
	 * - **Tab**: Entry Settings
	 * - **Documentation**: https://prismic.io/docs/fields/number
	 */
	price_multiple_books: prismic.NumberField;
	
	/**
	 * Shipping Address - Name field in *Enter Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: enter_page.shipping_name
	 * - **Tab**: Entry Settings
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	shipping_name: prismic.KeyTextField;
	
	/**
	 * Shipping Address - Street field in *Enter Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: enter_page.shipping_street
	 * - **Tab**: Entry Settings
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	shipping_street: prismic.KeyTextField;
	
	/**
	 * Shipping Address - Town field in *Enter Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: enter_page.shipping_town
	 * - **Tab**: Entry Settings
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	shipping_town: prismic.KeyTextField;
	
	/**
	 * Shipping Address - Postcode field in *Enter Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: enter_page.shipping_postcode
	 * - **Tab**: Entry Settings
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	shipping_postcode: prismic.KeyTextField;
	
	/**
	 * Shipping Address - Country field in *Enter Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: enter_page.shipping_country
	 * - **Tab**: Entry Settings
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	shipping_country: prismic.KeyTextField;/**
	 * Meta Title field in *Enter Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: enter_page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;
	
	/**
	 * Meta Description field in *Enter Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: enter_page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;
	
	/**
	 * Meta Image field in *Enter Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: enter_page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Enter Page document from Prismic
 *
 * - **API ID**: `enter_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EnterPageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<EnterPageDocumentData>, "enter_page", Lang>;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
	/**
	 * Copyright Text field in *Footer*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Maya Poetry Book Awards
	 * - **API ID Path**: footer.copyright_text
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	copyright_text: prismic.KeyTextField;
	
	/**
	 * Delivered By Text field in *Footer*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Lunim
	 * - **API ID Path**: footer.delivered_by_text
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	delivered_by_text: prismic.KeyTextField;
	
	/**
	 * Delivered By URL field in *Footer*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: https://lunim.io
	 * - **API ID Path**: footer.delivered_by_url
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	delivered_by_url: prismic.KeyTextField;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<FooterDocumentData>, "footer", Lang>;

type HomepageDocumentDataSlicesSlice = HeroSlice | RichTextSlice | FaqSlice | PrizeTableSlice | NewsletterSlice | ContactCardSlice

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
	/**
	 * Slice Zone field in *Homepage*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>;/**
	 * Meta Title field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: homepage.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;
	
	/**
	 * Meta Description field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: homepage.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;
	
	/**
	 * Meta Image field in *Homepage*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<HomepageDocumentData>, "homepage", Lang>;

type JudgePageDocumentDataSlicesSlice = HeroSlice | JudgeProfileSlice | RichTextSlice

/**
 * Content for Judge Page documents
 */
interface JudgePageDocumentData {
	/**
	 * Slice Zone field in *Judge Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: judge_page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<JudgePageDocumentDataSlicesSlice>;/**
	 * Meta Title field in *Judge Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: judge_page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;
	
	/**
	 * Meta Description field in *Judge Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: judge_page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;
	
	/**
	 * Meta Image field in *Judge Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: judge_page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Judge Page document from Prismic
 *
 * - **API ID**: `judge_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type JudgePageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<JudgePageDocumentData>, "judge_page", Lang>;

type PastWinnersPageDocumentDataSlicesSlice = HeroSlice | RichTextSlice | WinnersGridSlice

/**
 * Content for Past Winners Page documents
 */
interface PastWinnersPageDocumentData {
	/**
	 * Slice Zone field in *Past Winners Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: past_winners_page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<PastWinnersPageDocumentDataSlicesSlice>;/**
	 * Meta Title field in *Past Winners Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: past_winners_page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;
	
	/**
	 * Meta Description field in *Past Winners Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: past_winners_page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;
	
	/**
	 * Meta Image field in *Past Winners Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: past_winners_page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Past Winners Page document from Prismic
 *
 * - **API ID**: `past_winners_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PastWinnersPageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<PastWinnersPageDocumentData>, "past_winners_page", Lang>;

type PastWinnersYearDocumentDataSlicesSlice = HeroSlice | WinnersGridSlice | RichTextSlice

/**
 * Item in *Past Winners Year → Winners*
 */
export interface PastWinnersYearDocumentDataWinnersItem {
	/**
	 * Prize Level field in *Past Winners Year → Winners*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: Select prize level
	 * - **API ID Path**: past_winners_year.winners[].prize_level
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	prize_level: prismic.SelectField<"1st Place" | "2nd Place" | "3rd Place" | "Children's">;
	
	/**
	 * Book Title field in *Past Winners Year → Winners*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: past_winners_year.winners[].book_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	book_title: prismic.KeyTextField;
	
	/**
	 * Author field in *Past Winners Year → Winners*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: past_winners_year.winners[].author
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	author: prismic.KeyTextField;
	
	/**
	 * Co-Author (optional) field in *Past Winners Year → Winners*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: past_winners_year.winners[].author_2
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	author_2: prismic.KeyTextField;
	
	/**
	 * Location field in *Past Winners Year → Winners*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: past_winners_year.winners[].location
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	location: prismic.KeyTextField;
	
	/**
	 * Cover Image field in *Past Winners Year → Winners*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: past_winners_year.winners[].cover_image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	cover_image: prismic.ImageField<never>;
	
	/**
	 * Amazon URL field in *Past Winners Year → Winners*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: past_winners_year.winners[].amazon_url
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	amazon_url: prismic.KeyTextField;
}

/**
 * Item in *Past Winners Year → Shortlist*
 */
export interface PastWinnersYearDocumentDataShortlistItem {
	/**
	 * Book Title field in *Past Winners Year → Shortlist*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: past_winners_year.shortlist[].book_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	book_title: prismic.KeyTextField;
	
	/**
	 * Author field in *Past Winners Year → Shortlist*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: past_winners_year.shortlist[].author
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	author: prismic.KeyTextField;
	
	/**
	 * Location field in *Past Winners Year → Shortlist*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: past_winners_year.shortlist[].location
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	location: prismic.KeyTextField;
}

/**
 * Item in *Past Winners Year → Longlist*
 */
export interface PastWinnersYearDocumentDataLonglistItem {
	/**
	 * Book Title field in *Past Winners Year → Longlist*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: past_winners_year.longlist[].book_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	book_title: prismic.KeyTextField;
	
	/**
	 * Author field in *Past Winners Year → Longlist*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: past_winners_year.longlist[].author
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	author: prismic.KeyTextField;
	
	/**
	 * Location field in *Past Winners Year → Longlist*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: past_winners_year.longlist[].location
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	location: prismic.KeyTextField;
}

/**
 * Content for Past Winners Year documents
 */
interface PastWinnersYearDocumentData {
	/**
	 * Year field in *Past Winners Year*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: 2025
	 * - **API ID Path**: past_winners_year.year
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/number
	 */
	year: prismic.NumberField;
	
	/**
	 * Slice Zone field in *Past Winners Year*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: past_winners_year.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<PastWinnersYearDocumentDataSlicesSlice>;/**
	 * Winners field in *Past Winners Year*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: past_winners_year.winners[]
	 * - **Tab**: Winners
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	winners: prismic.GroupField<Simplify<PastWinnersYearDocumentDataWinnersItem>>;/**
	 * Shortlist field in *Past Winners Year*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: past_winners_year.shortlist[]
	 * - **Tab**: Shortlist
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	shortlist: prismic.GroupField<Simplify<PastWinnersYearDocumentDataShortlistItem>>;/**
	 * Longlist field in *Past Winners Year*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: past_winners_year.longlist[]
	 * - **Tab**: Longlist
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	longlist: prismic.GroupField<Simplify<PastWinnersYearDocumentDataLonglistItem>>;/**
	 * Meta Title field in *Past Winners Year*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: past_winners_year.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;
	
	/**
	 * Meta Description field in *Past Winners Year*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: past_winners_year.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;
	
	/**
	 * Meta Image field in *Past Winners Year*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: past_winners_year.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Past Winners Year document from Prismic
 *
 * - **API ID**: `past_winners_year`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PastWinnersYearDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<PastWinnersYearDocumentData>, "past_winners_year", Lang>;

type PrimaryNavigationDocumentDataSlicesSlice = NavigationMenuSlice

/**
 * Content for Primary Navigation documents
 */
interface PrimaryNavigationDocumentData {
	/**
	 * Slice Zone field in *Primary Navigation*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: primary_navigation.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<PrimaryNavigationDocumentDataSlicesSlice>;
}

/**
 * Primary Navigation document from Prismic
 *
 * - **API ID**: `primary_navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PrimaryNavigationDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<PrimaryNavigationDocumentData>, "primary_navigation", Lang>;

export type AllDocumentTypes = EnterPageDocument | FooterDocument | HomepageDocument | JudgePageDocument | PastWinnersPageDocument | PastWinnersYearDocument | PrimaryNavigationDocument;

/**
 * Primary content in *ContactCard → Default → Primary*
 */
export interface ContactCardSliceDefaultPrimary {
	/**
	 * Title field in *ContactCard → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Contact Us
	 * - **API ID Path**: contact_card.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Description field in *ContactCard → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Get in touch with us...
	 * - **API ID Path**: contact_card.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
}

/**
 * Default variation for ContactCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default contact form
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactCardSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ContactCardSliceDefaultPrimary>, never>;

/**
 * Slice variation for *ContactCard*
 */
type ContactCardSliceVariation = ContactCardSliceDefault

/**
 * ContactCard Shared Slice
 *
 * - **API ID**: `contact_card`
 * - **Description**: Contact form card
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactCardSlice = prismic.SharedSlice<"contact_card", ContactCardSliceVariation>;

/**
 * Item in *Faq → Default → Primary → FAQ Items*
 */
export interface FaqSliceDefaultPrimaryItemsItem {
	/**
	 * Question field in *Faq → Default → Primary → FAQ Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Enter question...
	 * - **API ID Path**: faq.default.primary.items[].question
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	question: prismic.KeyTextField;
	
	/**
	 * Answer field in *Faq → Default → Primary → FAQ Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Enter answer...
	 * - **API ID Path**: faq.default.primary.items[].answer
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	answer: prismic.RichTextField;
}

/**
 * Primary content in *Faq → Default → Primary*
 */
export interface FaqSliceDefaultPrimary {
	/**
	 * Title field in *Faq → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: FAQ
	 * - **API ID Path**: faq.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * FAQ Items field in *Faq → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	items: prismic.GroupField<Simplify<FaqSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default FAQ accordion
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<"default", Simplify<FaqSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation = FaqSliceDefault

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: Frequently asked questions accordion
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;

/**
 * Primary content in *Footer → Default → Primary*
 */
export interface FooterSliceDefaultPrimary {
	/**
	 * Copyright Text field in *Footer → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Maya Poetry Book Awards
	 * - **API ID Path**: footer.default.primary.copyright_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	copyright_text: prismic.KeyTextField;
	
	/**
	 * Delivered By Text field in *Footer → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Lunim
	 * - **API ID Path**: footer.default.primary.delivered_by_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	delivered_by_text: prismic.KeyTextField;
	
	/**
	 * Delivered By URL field in *Footer → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: https://lunim.io
	 * - **API ID Path**: footer.default.primary.delivered_by_url
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	delivered_by_url: prismic.KeyTextField;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default footer
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<"default", Simplify<FooterSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Site footer
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSlice = prismic.SharedSlice<"footer", FooterSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
	/**
	 * Title field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Enter hero title...
	 * - **API ID Path**: hero.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * Subtitle field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Enter subtitle...
	 * - **API ID Path**: hero.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	subtitle: prismic.RichTextField;
	
	/**
	 * CTA Button Text field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Enter button text...
	 * - **API ID Path**: hero.default.primary.cta_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_text: prismic.KeyTextField;
	
	/**
	 * CTA Button Link field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: /enter
	 * - **API ID Path**: hero.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_link: prismic.KeyTextField;
	
	/**
	 * Variant field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: Select variant
	 * - **Default Value**: default
	 * - **API ID Path**: hero.default.primary.variant
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	variant: prismic.SelectField<"default" | "home" | "small", "filled">;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default hero section
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<"default", Simplify<HeroSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero section with title, subtitle, and call-to-action
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *JudgeProfile → Default → Primary → Books*
 */
export interface JudgeProfileSliceDefaultPrimaryBooksItem {
	/**
	 * Book Title field in *JudgeProfile → Default → Primary → Books*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Enter book title...
	 * - **API ID Path**: judge_profile.default.primary.books[].book_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	book_title: prismic.KeyTextField;
	
	/**
	 * Book Cover field in *JudgeProfile → Default → Primary → Books*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: judge_profile.default.primary.books[].book_image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	book_image: prismic.ImageField<never>;
	
	/**
	 * Amazon URL field in *JudgeProfile → Default → Primary → Books*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: https://amazon.com/...
	 * - **API ID Path**: judge_profile.default.primary.books[].book_amazon_url
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	book_amazon_url: prismic.KeyTextField;
	
	/**
	 * Description field in *JudgeProfile → Default → Primary → Books*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Short description...
	 * - **API ID Path**: judge_profile.default.primary.books[].book_description
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	book_description: prismic.KeyTextField;
}

/**
 * Primary content in *JudgeProfile → Default → Primary*
 */
export interface JudgeProfileSliceDefaultPrimary {
	/**
	 * Name field in *JudgeProfile → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Judge name...
	 * - **API ID Path**: judge_profile.default.primary.name
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	name: prismic.KeyTextField;
	
	/**
	 * Title field in *JudgeProfile → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Author, Entrepreneur...
	 * - **API ID Path**: judge_profile.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Location field in *JudgeProfile → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Cardiff, Wales
	 * - **API ID Path**: judge_profile.default.primary.location
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	location: prismic.KeyTextField;
	
	/**
	 * Portrait field in *JudgeProfile → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: judge_profile.default.primary.portrait
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	portrait: prismic.ImageField<never>;
	
	/**
	 * Biography field in *JudgeProfile → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Enter biography...
	 * - **API ID Path**: judge_profile.default.primary.bio
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	bio: prismic.RichTextField;
	
	/**
	 * Entrepreneurial History field in *JudgeProfile → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Enter entrepreneurial history...
	 * - **API ID Path**: judge_profile.default.primary.entrepreneurial_history
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	entrepreneurial_history: prismic.RichTextField;
	
	/**
	 * Literary History field in *JudgeProfile → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Enter literary history...
	 * - **API ID Path**: judge_profile.default.primary.literary_history
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	literary_history: prismic.RichTextField;
	
	/**
	 * Books field in *JudgeProfile → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: judge_profile.default.primary.books[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	books: prismic.GroupField<Simplify<JudgeProfileSliceDefaultPrimaryBooksItem>>;
}

/**
 * Default variation for JudgeProfile Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default judge profile
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type JudgeProfileSliceDefault = prismic.SharedSliceVariation<"default", Simplify<JudgeProfileSliceDefaultPrimary>, never>;

/**
 * Slice variation for *JudgeProfile*
 */
type JudgeProfileSliceVariation = JudgeProfileSliceDefault

/**
 * JudgeProfile Shared Slice
 *
 * - **API ID**: `judge_profile`
 * - **Description**: Judge biography and book showcase
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type JudgeProfileSlice = prismic.SharedSlice<"judge_profile", JudgeProfileSliceVariation>;

/**
 * Item in *NavigationMenu → Default → Primary → Navigation Links*
 */
export interface NavigationMenuSliceDefaultPrimaryNavLinksItem {
	/**
	 * Label field in *NavigationMenu → Default → Primary → Navigation Links*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Link text
	 * - **API ID Path**: navigation_menu.default.primary.nav_links[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
	
	/**
	 * URL field in *NavigationMenu → Default → Primary → Navigation Links*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: /page
	 * - **API ID Path**: navigation_menu.default.primary.nav_links[].url
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	url: prismic.KeyTextField;
}

/**
 * Item in *NavigationMenu → Default → Primary → Past Winners Years*
 */
export interface NavigationMenuSliceDefaultPrimaryPastWinnersYearsItem {
	/**
	 * Year field in *NavigationMenu → Default → Primary → Past Winners Years*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: 2025
	 * - **API ID Path**: navigation_menu.default.primary.past_winners_years[].year
	 * - **Documentation**: https://prismic.io/docs/fields/number
	 */
	year: prismic.NumberField;
}

/**
 * Primary content in *NavigationMenu → Default → Primary*
 */
export interface NavigationMenuSliceDefaultPrimary {
	/**
	 * Brand Name field in *NavigationMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Maya
	 * - **API ID Path**: navigation_menu.default.primary.brand_name
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	brand_name: prismic.KeyTextField;
	
	/**
	 * Brand Logo field in *NavigationMenu → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation_menu.default.primary.brand_logo
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	brand_logo: prismic.ImageField<never>;
	
	/**
	 * Navigation Links field in *NavigationMenu → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation_menu.default.primary.nav_links[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	nav_links: prismic.GroupField<Simplify<NavigationMenuSliceDefaultPrimaryNavLinksItem>>;
	
	/**
	 * Past Winners Years field in *NavigationMenu → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation_menu.default.primary.past_winners_years[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	past_winners_years: prismic.GroupField<Simplify<NavigationMenuSliceDefaultPrimaryPastWinnersYearsItem>>;
}

/**
 * Default variation for NavigationMenu Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default navigation menu
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NavigationMenuSliceDefault = prismic.SharedSliceVariation<"default", Simplify<NavigationMenuSliceDefaultPrimary>, never>;

/**
 * Slice variation for *NavigationMenu*
 */
type NavigationMenuSliceVariation = NavigationMenuSliceDefault

/**
 * NavigationMenu Shared Slice
 *
 * - **API ID**: `navigation_menu`
 * - **Description**: Site navigation menu
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NavigationMenuSlice = prismic.SharedSlice<"navigation_menu", NavigationMenuSliceVariation>;

/**
 * Primary content in *Newsletter → Default → Primary*
 */
export interface NewsletterSliceDefaultPrimary {
	/**
	 * Title field in *Newsletter → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Newsletter
	 * - **API ID Path**: newsletter.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Description field in *Newsletter → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Stay updated with our latest news...
	 * - **API ID Path**: newsletter.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
}

/**
 * Default variation for Newsletter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default newsletter signup
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NewsletterSliceDefault = prismic.SharedSliceVariation<"default", Simplify<NewsletterSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Newsletter*
 */
type NewsletterSliceVariation = NewsletterSliceDefault

/**
 * Newsletter Shared Slice
 *
 * - **API ID**: `newsletter`
 * - **Description**: Newsletter signup form
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NewsletterSlice = prismic.SharedSlice<"newsletter", NewsletterSliceVariation>;

/**
 * Item in *PrizeTable → Default → Primary → Prize Items*
 */
export interface PrizeTableSliceDefaultPrimaryItemsItem {
	/**
	 * Prize Level field in *PrizeTable → Default → Primary → Prize Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 1st Place
	 * - **API ID Path**: prize_table.default.primary.items[].level
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	level: prismic.KeyTextField;
	
	/**
	 * Amount field in *PrizeTable → Default → Primary → Prize Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: £800
	 * - **API ID Path**: prize_table.default.primary.items[].amount
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	amount: prismic.KeyTextField;
}

/**
 * Primary content in *PrizeTable → Default → Primary*
 */
export interface PrizeTableSliceDefaultPrimary {
	/**
	 * Prize Items field in *PrizeTable → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: prize_table.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	items: prismic.GroupField<Simplify<PrizeTableSliceDefaultPrimaryItemsItem>>;
	
	/**
	 * Note field in *PrizeTable → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Additional prize information...
	 * - **API ID Path**: prize_table.default.primary.note
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	note: prismic.KeyTextField;
}

/**
 * Default variation for PrizeTable Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default prize table
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PrizeTableSliceDefault = prismic.SharedSliceVariation<"default", Simplify<PrizeTableSliceDefaultPrimary>, never>;

/**
 * Slice variation for *PrizeTable*
 */
type PrizeTableSliceVariation = PrizeTableSliceDefault

/**
 * PrizeTable Shared Slice
 *
 * - **API ID**: `prize_table`
 * - **Description**: Table displaying prize amounts
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PrizeTableSlice = prismic.SharedSlice<"prize_table", PrizeTableSliceVariation>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
	/**
	 * Content field in *RichText → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Enter content...
	 * - **API ID Path**: rich_text.default.primary.content
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default rich text block
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<"default", Simplify<RichTextSliceDefaultPrimary>, never>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: Rich text content block
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSlice = prismic.SharedSlice<"rich_text", RichTextSliceVariation>;

/**
 * Item in *WinnersGrid → Default → Primary → Winners*
 */
export interface WinnersGridSliceDefaultPrimaryItemsItem {
	/**
	 * Prize Level field in *WinnersGrid → Default → Primary → Winners*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: Select prize level
	 * - **API ID Path**: winners_grid.default.primary.items[].prize_level
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	prize_level: prismic.SelectField<"1st Place" | "2nd Place" | "3rd Place" | "Children's">;
	
	/**
	 * Book Title field in *WinnersGrid → Default → Primary → Winners*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Enter book title...
	 * - **API ID Path**: winners_grid.default.primary.items[].book_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	book_title: prismic.KeyTextField;
	
	/**
	 * Author field in *WinnersGrid → Default → Primary → Winners*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Enter author name...
	 * - **API ID Path**: winners_grid.default.primary.items[].author
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	author: prismic.KeyTextField;
	
	/**
	 * Author 2 (if co-authored) field in *WinnersGrid → Default → Primary → Winners*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Enter second author name...
	 * - **API ID Path**: winners_grid.default.primary.items[].author_2
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	author_2: prismic.KeyTextField;
	
	/**
	 * Location field in *WinnersGrid → Default → Primary → Winners*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Enter location...
	 * - **API ID Path**: winners_grid.default.primary.items[].location
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	location: prismic.KeyTextField;
	
	/**
	 * Cover Image field in *WinnersGrid → Default → Primary → Winners*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: winners_grid.default.primary.items[].cover_image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	cover_image: prismic.ImageField<never>;
	
	/**
	 * Amazon URL field in *WinnersGrid → Default → Primary → Winners*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: https://amazon.com/...
	 * - **API ID Path**: winners_grid.default.primary.items[].amazon_url
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	amazon_url: prismic.KeyTextField;
}

/**
 * Primary content in *WinnersGrid → Default → Primary*
 */
export interface WinnersGridSliceDefaultPrimary {
	/**
	 * Year field in *WinnersGrid → Default → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: 2025
	 * - **API ID Path**: winners_grid.default.primary.year
	 * - **Documentation**: https://prismic.io/docs/fields/number
	 */
	year: prismic.NumberField;
	
	/**
	 * Winners field in *WinnersGrid → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: winners_grid.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	items: prismic.GroupField<Simplify<WinnersGridSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for WinnersGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default winners grid
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WinnersGridSliceDefault = prismic.SharedSliceVariation<"default", Simplify<WinnersGridSliceDefaultPrimary>, never>;

/**
 * Slice variation for *WinnersGrid*
 */
type WinnersGridSliceVariation = WinnersGridSliceDefault

/**
 * WinnersGrid Shared Slice
 *
 * - **API ID**: `winners_grid`
 * - **Description**: Grid displaying award winners
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WinnersGridSlice = prismic.SharedSlice<"winners_grid", WinnersGridSliceVariation>;

declare module "@prismicio/client" {
	interface CreateClient {
		(repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
	}
	
	interface CreateWriteClient {
		(repositoryNameOrEndpoint: string, options: prismic.WriteClientConfig): prismic.WriteClient<AllDocumentTypes>;
	}
	
	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}
	
	namespace Content {
		export type {
			EnterPageDocument,
			EnterPageDocumentData,
			EnterPageDocumentDataSlicesSlice,
			FooterDocument,
			FooterDocumentData,
			HomepageDocument,
			HomepageDocumentData,
			HomepageDocumentDataSlicesSlice,
			JudgePageDocument,
			JudgePageDocumentData,
			JudgePageDocumentDataSlicesSlice,
			PastWinnersPageDocument,
			PastWinnersPageDocumentData,
			PastWinnersPageDocumentDataSlicesSlice,
			PastWinnersYearDocument,
			PastWinnersYearDocumentData,
			PastWinnersYearDocumentDataSlicesSlice,
			PastWinnersYearDocumentDataWinnersItem,
			PastWinnersYearDocumentDataShortlistItem,
			PastWinnersYearDocumentDataLonglistItem,
			PrimaryNavigationDocument,
			PrimaryNavigationDocumentData,
			PrimaryNavigationDocumentDataSlicesSlice,
			AllDocumentTypes,
			ContactCardSlice,
			ContactCardSliceDefaultPrimary,
			ContactCardSliceVariation,
			ContactCardSliceDefault,
			FaqSlice,
			FaqSliceDefaultPrimaryItemsItem,
			FaqSliceDefaultPrimary,
			FaqSliceVariation,
			FaqSliceDefault,
			FooterSlice,
			FooterSliceDefaultPrimary,
			FooterSliceVariation,
			FooterSliceDefault,
			HeroSlice,
			HeroSliceDefaultPrimary,
			HeroSliceVariation,
			HeroSliceDefault,
			JudgeProfileSlice,
			JudgeProfileSliceDefaultPrimaryBooksItem,
			JudgeProfileSliceDefaultPrimary,
			JudgeProfileSliceVariation,
			JudgeProfileSliceDefault,
			NavigationMenuSlice,
			NavigationMenuSliceDefaultPrimaryNavLinksItem,
			NavigationMenuSliceDefaultPrimaryPastWinnersYearsItem,
			NavigationMenuSliceDefaultPrimary,
			NavigationMenuSliceVariation,
			NavigationMenuSliceDefault,
			NewsletterSlice,
			NewsletterSliceDefaultPrimary,
			NewsletterSliceVariation,
			NewsletterSliceDefault,
			PrizeTableSlice,
			PrizeTableSliceDefaultPrimaryItemsItem,
			PrizeTableSliceDefaultPrimary,
			PrizeTableSliceVariation,
			PrizeTableSliceDefault,
			RichTextSlice,
			RichTextSliceDefaultPrimary,
			RichTextSliceVariation,
			RichTextSliceDefault,
			WinnersGridSlice,
			WinnersGridSliceDefaultPrimaryItemsItem,
			WinnersGridSliceDefaultPrimary,
			WinnersGridSliceVariation,
			WinnersGridSliceDefault
		}
	}
}