// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  rich_text: dynamic(() => import("./RichText")),
  faq: dynamic(() => import("./Faq")),
  prize_table: dynamic(() => import("./PrizeTable")),
  winners_grid: dynamic(() => import("./WinnersGrid")),
  judge_profile: dynamic(() => import("./JudgeProfile")),
  newsletter: dynamic(() => import("./Newsletter")),
  contact_card: dynamic(() => import("./ContactCard")),
  navigation_menu: dynamic(() => import("./NavigationMenu")),
  footer: dynamic(() => import("./Footer")),
  about_with_newsletter_and_contact: dynamic(() => import("./AboutWithNewsletterAndContact")),
};
