// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_intro: dynamic(() => import("./AboutIntro")),
  about_section: dynamic(() => import("./AboutSection")),
  closed_hero: dynamic(() => import("./ClosedHero")),
  contact_card: dynamic(() => import("./ContactCard")),
  faq: dynamic(() => import("./Faq")),
  footer: dynamic(() => import("./Footer")),
  hero: dynamic(() => import("./Hero")),
  judge_profile: dynamic(() => import("./JudgeProfile")),
  listing: dynamic(() => import("./Listing")),
  navigation_menu: dynamic(() => import("./NavigationMenu")),
  newsletter: dynamic(() => import("./Newsletter")),
  prize_section: dynamic(() => import("./PrizeSection")),
  prize_table: dynamic(() => import("./PrizeTable")),
  rich_text: dynamic(() => import("./RichText")),
  winners_grid: dynamic(() => import("./WinnersGrid")),
};
